apiVersion: v1
kind: Namespace
metadata:
  name: saga-ns
---
apiVersion: v1
kind: Service
metadata:
  namespace: saga-ns
  name: saga-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: saga-stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: saga-ns
  labels:
    app: saga-stress
  name: saga-web
spec:
  selector:
    matchLabels:
      app: saga-stress
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: saga-stress
    spec:
      containers:
      - image: sagarikapadhy/spring-email-scheduler:1.0.0
        name: stresser
          ports:
              - containerPort: 80
          resources:
            requests:
              cpu: 0.2
        ---
        apiVersion: autoscaling/v1
        kind: HorizontalPodAutoscaler
        metadata:
          name: saga-hpa
          namespace: saga-ns
        spec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: saga-web
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 50